label.new
Creates new label object
label.new(x, y, text, xloc, yloc, color, style, textcolor, size, textalign, tooltip) → series[label]
Example

var label1 = label.new(bar_index, low, text="Hello, world!", style=label.style_circle)
label.set_x(label1, 0)
label.set_xloc(label1, time, xloc.bar_time)
label.set_color(label1, color.red)
label.set_size(label1, size.large)


//

https://www.tradingview.com/pine-script-reference/#fun_label{dot}new

